### ISSUE TITLE
safe_gpu doesn't work with PyTorch DDP mode

### ISSUE THREAD

**Issue by mimunzar** [BUTSpeechFIT/safe_gpu#1]
On SGE server the GPUs are set in Exclusive Process Mode. This mode makes sure that there is just one process running on any GPU at the time. When initializing GPUOwner the class allocates a tensor on assigned GPUs. The tensor than prevents training for spawned processes due to Exclusive Process Mode (more than one process allocates memory on a GPU).

The error is indicated by the following message:
```
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Line which causes the issue:
https://github.com/BUTSpeechFIT/safe_gpu/blob/6fc8f69600b8500828d20f7aac67ce72abe323ca/safe_gpu/safe_gpu.py#L140

**Comment by ibenes** [comment]
This is the intended behaviour, `GPUOwner` really "owns" the GPU, thus it needs to be instantiated in the process that's going to use the GPU. I believe this should be doable with PyTorch DDP. It's certainly doable with Horovod, see README.
